### ISSUE TITLE
New Feature - Add PWA installation

### ISSUE THREAD

**Issue by BlackCatDeployment** [okieselbach/Autopilot-Manager#11]
Hello,

First of all, thanks for your huge work, it simplify my life with Autopilot enrollment!
I have an idea for a new feature ; is it possible to turn the APM website to a Progressive Web App (PWA)?
It could be interesting to have an app available on my device instead of using my web browser.

Regards

**Comment by okieselbach** [comment]
Oh, not a bad idea, but I need to look into it, never done a PWA app before. I'm more or less a part time developer :-) so have to look into it and talk to some dev friends. I will evaluate it.

Thanks for the suggestion.

btw. an upcoming release will have some more capabilities like re-register mode (cleanup of old Autopilot hashes in case of break-fix, e.g. motherboard change) and also the option to send Audit data to a Log analytics instance.

best,
Oliver

**Comment by BlackCatDeployment** [comment]
Thanks for your reply :)
And for the breaking new about the upcoming release! Can't wait!

**Comment by okieselbach** [comment]
no time to invest in research for a PWA here. So close the ticket for now.
