### ISSUE TITLE
Improvement - Approval Mode = True, QR Code redirects on the device's approval page

### ISSUE THREAD

**Issue by BlackCatDeployment** [okieselbach/Autopilot-Manager#12]
Hello,

Currently, when the Approval Mode (AppConfig:AutopilotManagerConfig:ApprovalMode) is set to True, when I flash the QR Code on the device, it redirects me on an unusable web page.
It should be great to automatically redirect on the device's approval web page. With that, I just have to select the correct Group Tag and submit the record.

Thanks.

**Comment by okieselbach** [comment]
no change planed here but site redirects to a more meaningful site telling no self-service configured/allowed
