### ISSUE TITLE
Improvement - Home Page customization

### ISSUE THREAD

**Issue by BlackCatDeployment** [okieselbach/Autopilot-Manager#13]
Hello,

I saw that it's now possible to configure a little more the home page, which is really great!
Could you allow more customizations like:
- the Helpdesk sentence:
![image](https://user-images.githubusercontent.com/12493050/144248377-1fcba74e-f3a6-4e25-b648-26567a77c8d1.png)

- the import command url:
Even if you added the parameter "AppConfig:AutopilotManagerConfig:HomepageImportCommandUrls", I wrapped curl and ap.exe commands, so my local ITs don't use them by default.
![image](https://user-images.githubusercontent.com/12493050/144249148-8bedb867-07d7-4520-8972-dc510a7498e9.png)

It should be great to totally customize the import commands.

- Add a logo and color theme
Extra bonus: Clearly not a priority :)

Thanks

**Comment by okieselbach** [comment]
Stay tuned something is upcoming which might please you :-D.
