### ISSUE TITLE
Cannot access Approvals page

### ISSUE THREAD

**Issue by llrowland01** [okieselbach/Autopilot-Manager#20]
I have the app up and running, but I'm not able to get to the Approval screens.  I get Access Denied.   I have the token configured per the setup blog.  My user's account is in the Approvers Group, and I have verified the Group ID is correct.  Not sure where to look next

**Comment by okieselbach** [comment]
This can happen if the token is too large (too many group memberships). But there is a way to prevent this by switching to the groupMembershipClaim to ApplicationGroup and then addint the 3 Groups to the Enterprise Application.

see also here: https://github.com/okieselbach/Autopilot-Manager/discussions/15
